// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// capybara.cpp
doubles_matrix<> center_variables_(const doubles_matrix<> & V_r, const doubles & w_r, const list & klist, const double & tol, const size_t & max_iter, const size_t & iter_interrupt, const size_t & iter_ssr, const size_t & accel_start, const double & project_tol_factor, const double & grand_accel_tol, const double & project_group_tol, const double & irons_tuck_tol, const size_t & grand_accel_interval, const size_t & irons_tuck_interval, const size_t & ssr_check_interval, const double & convergence_factor, const double & tol_multiplier);
extern "C" SEXP _capybara_center_variables_(SEXP V_r, SEXP w_r, SEXP klist, SEXP tol, SEXP max_iter, SEXP iter_interrupt, SEXP iter_ssr, SEXP accel_start, SEXP project_tol_factor, SEXP grand_accel_tol, SEXP project_group_tol, SEXP irons_tuck_tol, SEXP grand_accel_interval, SEXP irons_tuck_interval, SEXP ssr_check_interval, SEXP convergence_factor, SEXP tol_multiplier) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(center_variables_(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(V_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(w_r), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(klist), cpp4r::as_cpp<cpp4r::decay_t<const double &>>(tol), cpp4r::as_cpp<cpp4r::decay_t<const size_t &>>(max_iter), cpp4r::as_cpp<cpp4r::decay_t<const size_t &>>(iter_interrupt), cpp4r::as_cpp<cpp4r::decay_t<const size_t &>>(iter_ssr), cpp4r::as_cpp<cpp4r::decay_t<const size_t &>>(accel_start), cpp4r::as_cpp<cpp4r::decay_t<const double &>>(project_tol_factor), cpp4r::as_cpp<cpp4r::decay_t<const double &>>(grand_accel_tol), cpp4r::as_cpp<cpp4r::decay_t<const double &>>(project_group_tol), cpp4r::as_cpp<cpp4r::decay_t<const double &>>(irons_tuck_tol), cpp4r::as_cpp<cpp4r::decay_t<const size_t &>>(grand_accel_interval), cpp4r::as_cpp<cpp4r::decay_t<const size_t &>>(irons_tuck_interval), cpp4r::as_cpp<cpp4r::decay_t<const size_t &>>(ssr_check_interval), cpp4r::as_cpp<cpp4r::decay_t<const double &>>(convergence_factor), cpp4r::as_cpp<cpp4r::decay_t<const double &>>(tol_multiplier)));
  END_CPP4R
}
// capybara.cpp
list felm_fit_(const doubles_matrix<> & X_r, const doubles & y_r, const doubles & w_r, const list & FEs, const list & control);
extern "C" SEXP _capybara_felm_fit_(SEXP X_r, SEXP y_r, SEXP w_r, SEXP FEs, SEXP control) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(felm_fit_(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(X_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(y_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(w_r), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(FEs), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(control)));
  END_CPP4R
}
// capybara.cpp
list feglm_fit_(const doubles & beta_r, const doubles & eta_r, const doubles & y_r, const doubles_matrix<> & x_r, const doubles & wt_r, const double & theta, const std::string & family, const list & control, const list & k_list);
extern "C" SEXP _capybara_feglm_fit_(SEXP beta_r, SEXP eta_r, SEXP y_r, SEXP x_r, SEXP wt_r, SEXP theta, SEXP family, SEXP control, SEXP k_list) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(feglm_fit_(cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(beta_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(eta_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(y_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(x_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(wt_r), cpp4r::as_cpp<cpp4r::decay_t<const double &>>(theta), cpp4r::as_cpp<cpp4r::decay_t<const std::string &>>(family), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(control), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(k_list)));
  END_CPP4R
}
// capybara.cpp
doubles feglm_offset_fit_(const doubles & eta_r, const doubles & y_r, const doubles & offset_r, const doubles & wt_r, const std::string & family, const list & control, const list & k_list);
extern "C" SEXP _capybara_feglm_offset_fit_(SEXP eta_r, SEXP y_r, SEXP offset_r, SEXP wt_r, SEXP family, SEXP control, SEXP k_list) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(feglm_offset_fit_(cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(eta_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(y_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(offset_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(wt_r), cpp4r::as_cpp<cpp4r::decay_t<const std::string &>>(family), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(control), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(k_list)));
  END_CPP4R
}
// capybara.cpp
list fenegbin_fit_(const doubles_matrix<> & X_r, const doubles & y_r, const doubles & w_r, const list & FEs, const std::string & link, const doubles & beta_r, const doubles & eta_r, const double & init_theta, const list & control);
extern "C" SEXP _capybara_fenegbin_fit_(SEXP X_r, SEXP y_r, SEXP w_r, SEXP FEs, SEXP link, SEXP beta_r, SEXP eta_r, SEXP init_theta, SEXP control) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(fenegbin_fit_(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(X_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(y_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(w_r), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(FEs), cpp4r::as_cpp<cpp4r::decay_t<const std::string &>>(link), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(beta_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles &>>(eta_r), cpp4r::as_cpp<cpp4r::decay_t<const double &>>(init_theta), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(control)));
  END_CPP4R
}
// capybara.cpp
doubles_matrix<> group_sums_(const doubles_matrix<> & M_r, const doubles_matrix<> & w_r, const list & jlist);
extern "C" SEXP _capybara_group_sums_(SEXP M_r, SEXP w_r, SEXP jlist) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(group_sums_(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(M_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(w_r), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(jlist)));
  END_CPP4R
}
// capybara.cpp
doubles_matrix<> group_sums_spectral_(const doubles_matrix<> & M_r, const doubles_matrix<> & v_r, const doubles_matrix<> & w_r, const size_t K, const list & jlist);
extern "C" SEXP _capybara_group_sums_spectral_(SEXP M_r, SEXP v_r, SEXP w_r, SEXP K, SEXP jlist) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(group_sums_spectral_(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(M_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(v_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(w_r), cpp4r::as_cpp<cpp4r::decay_t<const size_t>>(K), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(jlist)));
  END_CPP4R
}
// capybara.cpp
doubles_matrix<> group_sums_var_(const doubles_matrix<> & M_r, const list & jlist);
extern "C" SEXP _capybara_group_sums_var_(SEXP M_r, SEXP jlist) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(group_sums_var_(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(M_r), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(jlist)));
  END_CPP4R
}
// capybara.cpp
doubles_matrix<> group_sums_cov_(const doubles_matrix<> & M_r, const doubles_matrix<> & N_r, const list & jlist);
extern "C" SEXP _capybara_group_sums_cov_(SEXP M_r, SEXP N_r, SEXP jlist) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(group_sums_cov_(cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(M_r), cpp4r::as_cpp<cpp4r::decay_t<const doubles_matrix<> &>>(N_r), cpp4r::as_cpp<cpp4r::decay_t<const list &>>(jlist)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_capybara_center_variables_",    (DL_FUNC) &_capybara_center_variables_,    17},
    {"_capybara_feglm_fit_",           (DL_FUNC) &_capybara_feglm_fit_,            9},
    {"_capybara_feglm_offset_fit_",    (DL_FUNC) &_capybara_feglm_offset_fit_,     7},
    {"_capybara_felm_fit_",            (DL_FUNC) &_capybara_felm_fit_,             5},
    {"_capybara_fenegbin_fit_",        (DL_FUNC) &_capybara_fenegbin_fit_,         9},
    {"_capybara_group_sums_",          (DL_FUNC) &_capybara_group_sums_,           3},
    {"_capybara_group_sums_cov_",      (DL_FUNC) &_capybara_group_sums_cov_,       3},
    {"_capybara_group_sums_spectral_", (DL_FUNC) &_capybara_group_sums_spectral_,  5},
    {"_capybara_group_sums_var_",      (DL_FUNC) &_capybara_group_sums_var_,       2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_capybara(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
