# Generated by cpp11: do not edit by hand

center_variables_ <- function(V_r, v_sum_r, w_r, klist, tol, maxiter, sum_v) {
  .Call(`_capybara_center_variables_`, V_r, v_sum_r, w_r, klist, tol, maxiter, sum_v)
}

get_alpha_ <- function(p_r, klist, tol) {
  .Call(`_capybara_get_alpha_`, p_r, klist, tol)
}

group_sums_ <- function(M_r, w_r, jlist) {
  .Call(`_capybara_group_sums_`, M_r, w_r, jlist)
}

group_sums_spectral_ <- function(M_r, v_r, w_r, K, jlist) {
  .Call(`_capybara_group_sums_spectral_`, M_r, v_r, w_r, K, jlist)
}

group_sums_var_ <- function(M_r, jlist) {
  .Call(`_capybara_group_sums_var_`, M_r, jlist)
}

group_sums_cov_ <- function(M_r, N_r, jlist) {
  .Call(`_capybara_group_sums_cov_`, M_r, N_r, jlist)
}

crossprod_ <- function(x, w, weighted, root_weights) {
  .Call(`_capybara_crossprod_`, x, w, weighted, root_weights)
}

gamma_ <- function(mx, hessian, j, ppsi, v, nt_full) {
  .Call(`_capybara_gamma_`, mx, hessian, j, ppsi, v, nt_full)
}

chol_crossprod_ <- function(x) {
  .Call(`_capybara_chol_crossprod_`, x)
}

chol2inv_ <- function(r) {
  .Call(`_capybara_chol2inv_`, r)
}

chol_ <- function(x) {
  .Call(`_capybara_chol_`, x)
}

qr_rank_ <- function(x) {
  .Call(`_capybara_qr_rank_`, x)
}

solve_bias_ <- function(beta_uncorr, hessian, nt, b) {
  .Call(`_capybara_solve_bias_`, beta_uncorr, hessian, nt, b)
}

solve_y_ <- function(a, x) {
  .Call(`_capybara_solve_y_`, a, x)
}

sandwich_ <- function(a, b) {
  .Call(`_capybara_sandwich_`, a, b)
}

update_beta_eta_ <- function(old, upd, param) {
  .Call(`_capybara_update_beta_eta_`, old, upd, param)
}

update_nu_ <- function(y, mu, mu_eta) {
  .Call(`_capybara_update_nu_`, y, mu, mu_eta)
}

solve_beta_ <- function(mx, mnu, wtilde, epsilon, weighted) {
  .Call(`_capybara_solve_beta_`, mx, mnu, wtilde, epsilon, weighted)
}

solve_eta_ <- function(mx, mnu, nu, beta) {
  .Call(`_capybara_solve_eta_`, mx, mnu, nu, beta)
}

solve_eta2_ <- function(yadj, myadj, offset, eta) {
  .Call(`_capybara_solve_eta2_`, yadj, myadj, offset, eta)
}

sqrt_ <- function(w) {
  .Call(`_capybara_sqrt_`, w)
}

pairwise_cor_ <- function(y, yhat) {
  .Call(`_capybara_pairwise_cor_`, y, yhat)
}
