# Generated by cpp11: do not edit by hand

center_variables_ <- function(V, w, klist, tol, maxiter) {
  .Call(`_capybara_center_variables_`, V, w, klist, tol, maxiter)
}

get_alpha_ <- function(p, klist, tol) {
  .Call(`_capybara_get_alpha_`, p, klist, tol)
}

group_sums_ <- function(M, w, jlist) {
  .Call(`_capybara_group_sums_`, M, w, jlist)
}

group_sums_spectral_ <- function(M, v, w, K, jlist) {
  .Call(`_capybara_group_sums_spectral_`, M, v, w, K, jlist)
}

group_sums_var_ <- function(M, jlist) {
  .Call(`_capybara_group_sums_var_`, M, jlist)
}

group_sums_cov_ <- function(M, N, jlist) {
  .Call(`_capybara_group_sums_cov_`, M, N, jlist)
}

pairwise_cor_ <- function(y, yhat) {
  .Call(`_capybara_pairwise_cor_`, y, yhat)
}
