# Generated by cpp11: do not edit by hand

check_linear_dependence_qr_ <- function(y, x, p) {
  .Call(`_capybara_check_linear_dependence_qr_`, y, x, p)
}

center_variables_r_ <- function(V_r, w_r, klist, tol, max_iter, iter_interrupt, iter_ssr) {
  .Call(`_capybara_center_variables_r_`, V_r, w_r, klist, tol, max_iter, iter_interrupt, iter_ssr)
}

felm_fit_ <- function(y_r, x_r, wt_r, control, k_list) {
  .Call(`_capybara_felm_fit_`, y_r, x_r, wt_r, control, k_list)
}

feglm_fit_ <- function(beta_r, eta_r, y_r, x_r, wt_r, theta, family, control, k_list) {
  .Call(`_capybara_feglm_fit_`, beta_r, eta_r, y_r, x_r, wt_r, theta, family, control, k_list)
}

feglm_offset_fit_ <- function(eta_r, y_r, offset_r, wt_r, family, control, k_list) {
  .Call(`_capybara_feglm_offset_fit_`, eta_r, y_r, offset_r, wt_r, family, control, k_list)
}

get_alpha_ <- function(p_r, klist, control) {
  .Call(`_capybara_get_alpha_`, p_r, klist, control)
}

group_sums_ <- function(M_r, w_r, jlist) {
  .Call(`_capybara_group_sums_`, M_r, w_r, jlist)
}

group_sums_spectral_ <- function(M_r, v_r, w_r, K, jlist) {
  .Call(`_capybara_group_sums_spectral_`, M_r, v_r, w_r, K, jlist)
}

group_sums_var_ <- function(M_r, jlist) {
  .Call(`_capybara_group_sums_var_`, M_r, jlist)
}

group_sums_cov_ <- function(M_r, N_r, jlist) {
  .Call(`_capybara_group_sums_cov_`, M_r, N_r, jlist)
}
