name: Clang-Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    
    steps:
      # Format C++ code first
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: pachadotdev/clang-format@v1.1
        with:
          version: '21'
          files: 'src/*.cpp src/*.h inst/include/*.h'
          auto-commit: true
          commit-message: 'style: format C++ code in R package'
